version: "3"

services:
  streamlit:
    image: blagnac
    build: ./
    profiles: ["front"]
    ports:
        - 8082:1234
    volumes:
      - ./:/app/
    command: streamlit run --server.port 1234 streamlit/Data_exploration.py
    environment:
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL

  scraper:
    image: blagnac
    build: ./
    profiles: ["back"]
    volumes:
      - ./:/app/
    command: python scrape.py


networks:
  default:
    name: nginx-proxy
    external: true
